### ISSUE TITLE
Post–Deliverable

### ISSUE THREAD

**Issue by ashtastic** [shakeel-nazir/simple-chat-app#12]
@ericadamski @goug0035 @shakeel-nazir @ashtastic

# Progress
- [x] Paper Wireframes
  - [x] 404 page
  - [x] Chat (main) page
  - [x] Members List
  - [x] Notifications
    - [x] Joined
    - [x] Left
- [ ] Interactive Wireframes
  - [ ] 404 page
  - [ ] Chat (main) page
  - [ ] Members List
  - [ ] Notifications
    - [ ] Joined
    - [ ] Left
- [ ] Complete Project
  - [ ] 404 page
  - [ ] Chat (main) page
  - [ ] Members List
  - [ ] Notifications
    - [ ] Joined
    - [ ] Left

# Issues
Completed: #3 , #4 , #5 , #6 ...

# Positives :+1:

+ I was proactive in getting my portion done so that my team members could have the weekend to collaborate with their portions of the project. (Ash)
+ Using Adobe XD was the bomb and it saved a wicked amount of time. (Ash)
+ I feel like I spent a lot of time researching and designing my paper wire frames. (Shak)
+ I feel like I communicated well with my team members.(Shak)
+ I set meetings and collaborated well with my teammates to make cohesive prototypes (Mary)
+ Using Adobe XD to create the prototype and slack to share our work saved tune of meeting time (Mary)

# Improvements :star:

+ My designs could have used more quality. (Ash)
+ I could have asked for more feedback on my actual designs. (Shak)
+ My design was last to me made and don't know it the flow worked (mary)

# Request for Feedback :ear:

+ How would putting a video behind our chat actually turn out? What are your thoughts on that? (Ash)
+ For the member list (#5) is it better to go with the standard horizontal list or would it work better taking a more creative approach like sliding from the bottom of the page? (Shak)
+ Is it possible to create a pop-up for the sign in page (Mary)

**Comment by ericadamski** [comment]
yes for all the question!
